api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: volcano
      prediction_raw:
        volcano: 0.7308942675590515
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
