api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: lakeside
      prediction_raw:
        lakeside: 0.0925227627158165
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
