version: 1
labels:
  - label: "WIP"
    title: "^(wip|WIP).*"
  - label: "type: enhancement"
    title: "^feat.*"
  - label: "type: fix"
    title: "^fix.*"
  - label: "type: chore"
    title: "^chore.*"
  - label: "type: ci"
    title: "^ci.*"
  - label: "type: documentation"
    title: "^docs.*"
  - label: "type: refactor"
    title: "^refactor.*"
  - label: "type: performance"
    title: "^perf.*"
  - label: "type: test"
    title: "^test.*"
