api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: oystercatcher
      prediction_raw:
        oystercatcher: 0.20533981919288635
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
