api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output: http://files.gladia.io/output/text/image/image-generation/dream-studio/example/output.png
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
