api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: NEGATIVE
      prediction_raw:
        label: LABEL_1
        score: 0.5460877418518066
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
