summary: 'Format the input string as an clean adress using geopy'


inputs_example:
  sentence:
    default_example: "Taj Mahal, Agra, Uttar Pradesh 282001"
    examples:
      - "Taj Mahal, Agra, Uttar Pradesh 282001"
