api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: hate-speech
      prediction_raw: hate-speech
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
