api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: Once, a group of frogs was roaming around the forest in search of
        water.
      prediction_raw:
      - Once, a group of frogs was roaming around the forest in search of water.
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
