api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: valley
      prediction_raw:
        valley: 0.08818889409303665
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
