api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: bannister
      prediction_raw:
        bannister: 0.15585002303123474
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
