api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: promontory
      prediction_raw:
        promontory: 0.14395612478256226
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
