summary: ''


inputs_example:
  text:
    default_example: "Лорем ипсум долор сит амет"
    examples:
      - "Лорем ипсум долор сит амет"

  language:
    default_example: "ru"
    examples:
      - "ru"
