summary: ''

inputs_example:
  image_url:
    default_example: "http://files.gladia.io/examples/image/text/ocr/testocr.png"
    examples:
      - "http://files.gladia.io/examples/image/text/ocr/testocr.png"
      - "http://files.gladia.io/examples/image/text/ocr/testocr.jpg"
      - "http://files.gladia.io/examples/image/text/ocr/testocr.gif"
  source_language:
    default_example: "eng"
    examples:
      - "eng"
      - "fra"
