api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: abaya
      prediction_raw:
        abaya: 0.08071760088205338
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
