api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: Text to correct.
      prediction_raw: Text to correct.
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
