summary: 'Format the input string as an clean adress using geopy'


inputs_example:
  latitude:
    default_example: 43.2965
    examples:
      - 43.2965
  longitude:
    default_example: 5.36978
    examples:
      - 5.36978
