api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: shovel
      prediction_raw:
        shovel: 0.1708516776561737
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
