summary: ''

inputs_example:
  sentence_1:
    default_example: "I like you."
    examples:
      - "I like you."

  sentence_2:
    default_example: "But it's not about you."
    examples:
      - "But it's not about you."
