api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: ' Clara'
      prediction_raw:
      - answer: ' Clara'
        end: 16
        score: 0.9977526664733887
        start: 10
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
