api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: paddle
      prediction_raw:
        paddle: 0.262510746717453
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
