summary: ''


inputs_example:
  image_url:
    default_example: "http://files.gladia.io/image/image/enhancement/enhancement_retouching.png"
    examples:
      - "http://files.gladia.io/image/image/enhancement/enhancement_retouching.png"
      - "http://files.gladia.io/image/image/enhancement/enhancement_retouching.jpg"
      - "http://files.gladia.io/image/image/enhancement/enhancement_low-light.png"
      - "http://files.gladia.io/image/image/enhancement/enhancement_low-light.jpg"
