api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: barrow
      prediction_raw:
        barrow: 0.12124842405319214
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
