api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: .
      prediction_raw:
        '!': 0.02144467830657959
        .: 0.9096482396125793
        ;: 0.056629203259944916
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
