api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: beacon
      prediction_raw:
        beacon: 0.12177004665136337
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
