api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: cliff
      prediction_raw:
        cliff: 0.10201084613800049
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
