api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: seashore
      prediction_raw:
        seashore: 0.04995758458971977
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
