summary: 'Classify the gender of a speaker from a speech sample'


inputs_example:
  audio_url:
    default_example: "http://files.gladia.io/examples/audio/text/audio-transcription/audio.mp3"
    examples:
      - "http://files.gladia.io/examples/audio/text/audio-transcription/audio.mp3"
      - "http://files.gladia.io/examples/audio/text/audio-transcription/audio.m4a"
      - "http://files.gladia.io/examples/audio/text/audio-transcription/audio.wav"
