api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: sandbar
      prediction_raw:
        sandbar: 0.0765710100531578
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
