api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: POSITIVE
      prediction_raw:
        label: POSITIVE
        score: 0.9998738765716553
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
