summary: 'Perform speaker diarization (audio segment detect per speaker) on audio files'


inputs_example:
  audio_url:
    default_example: "http://files.gladia.io/examples/audio/text/audio-transcription/audio.mp3"
    examples:
      - "http://files.gladia.io/examples/audio/text/audio-transcription/audio.mp3"
      - "http://files.gladia.io/examples/audio/text/audio-transcription/audio.m4a"
      - "http://files.gladia.io/examples/audio/text/audio-transcription/audio.wav"