summary: ''


inputs_example:
  context:
    default_example: "Once, a group of frogs was roaming around the forest in search of water."
    examples:
      - "Once, a group of frogs was roaming around the forest in search of water."
