api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: "Input text to start generation from\n                       </TextBlock>\n\
        \                "
      prediction_raw:
      - generated_text: "Input text to start generation from\n                   \
          \    </TextBlock>\n                "
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
