api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: alp
      prediction_raw:
        alp: 0.24459868669509888
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
