api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: 'This is a lot of 12 point text to test the

        ocr code and see if it works on

        all types

        of file format:

        The quick brown dog jumped over the

        lazy fox The quick brown dog jumped

        over the lazy fox. The quick brown dog

        jumped over the lazy fox. The quick

        brown dog jumped over the lazy fox.'
      prediction_raw:
      - This is a lot of 12 point text to test the
      - ocr code and see if it works on
      - all types
      - 'of file format:'
      - The quick brown dog jumped over the
      - lazy fox The quick brown dog jumped
      - over the lazy fox. The quick brown dog
      - jumped over the lazy fox. The quick
      - brown dog jumped over the lazy fox.
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
