api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: wing
      prediction_raw:
        wing: 0.09617836773395538
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
