api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: 
      prediction_raw: 
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: 'https://huggingface.co/pyannote'
license:
  content: "MIT License

Copyright (c) 2020 CNRS

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the \"Software\"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."
  link: 'https://github.com/pyannote/pyannote-audio/blob/develop/LICENSE'
  title: 'MIT License'
paper:
  authors: [Bredin, Laurent, Yin, Coria, Gelly, Korshunov, Lavechin, Fustes, Titeux, Bouaziz, Gill]
  citation: [
    "@inproceedings{Bredin2020,
      Title = {{pyannote.audio: neural building blocks for speaker diarization}},
      Author = {{Bredin}, Herv{\'e} and {Yin}, Ruiqing and {Coria}, Juan Manuel and {Gelly}, Gregory and {Korshunov}, Pavel and {Lavechin}, Marvin and {Fustes}, Diego and {Titeux}, Hadrien and {Bouaziz}, Wassim and {Gill}, Marie-Philippe},
      Booktitle = {ICASSP 2020, IEEE International Conference on Acoustics, Speech, and Signal Processing},
      Year = {2020},
    }",
    "@inproceedings{Bredin2021,
      Title = {{End-to-end speaker segmentation for overlap-aware resegmentation}},
      Author = {{Bredin}, Herv{\'e} and {Laurent}, Antoine},
      Booktitle = {Proc. Interspeech 2021},
      Year = {2021},
    }"
  ]
  link: 'https://arxiv.org/abs/1911.01255'
  title: 'pyannote.audio: neural building blocks for speaker diarization'
