summary: ''

inputs_example:
  text:
    default_example: "The Crown is a historical drama streaming television series about the reign of Queen Elizabeth II, created and principally written by Peter Morgan, and produced by Left Bank Pictures and Sony Pictures Television for Netflix."
    examples:
      - "The Crown is a historical drama streaming television series about the reign of Queen Elizabeth II, created and principally written by Peter Morgan, and produced by Left Bank Pictures and Sony Pictures Television for Netflix."

  top_k:
    default_example: 10
    examples:
      - 1
      - 10
      - 100
