api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: snowmobile
      prediction_raw:
        snowmobile: 0.09909936785697937
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
