summary: 'Replace the background of an image'


inputs_example:
  original_image_url:
    default_example: "http://files.gladia.io/examples/image/image/background-removal/owl2.png"
    examples:
      - "http://files.gladia.io/examples/image/image/background-removal/owl2.png"
      - "http://files.gladia.io/examples/image/image/background-removal/owl2.jpg"
      - "https://15pictures.com/wp-content/gallery/15-pictures-lions/lions-4.jpg"
  background_image_url:
    default_example: "https://img.lovepik.com/free-png/20210918/lovepik-green-forest-png-image_400203927_wh1200.png"
    examples:
      - "https://img.lovepik.com/free-png/20210918/lovepik-green-forest-png-image_400203927_wh1200.png"
  alignment:
    default_example: "center"
    examples:
      - "center"
      - "top"
      - "bottom"
      - "left"
      - "right"
      - "top-left"
      - "top-center"
      - "top-right"
      - "bottom-left"
      - "bottom-center"
      - "bottom-right"
      - "cropped"
