api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: tripod
      prediction_raw:
        tripod: 0.37666431069374084
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
