name: Deploy in SaaS

on:
  workflow_run:
    workflows: [Gladia Promote & deploy]
    types: [completed]

jobs:
  get-info:
    name: "Get information about the source run"
    runs-on: ubuntu-latest
    outputs:
      prNumber: ${{ steps.PR.outputs.number }}
      prLabel: ${{ steps.PR.outputs.pr_labels }}
      prTitle: ${{ steps.PR.outputs.pr_title }}
      prOutcome: ${{ steps.PR.outputs.outcome  }}

    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR
        with:
          sha: ${{ github.event.workflow_run.head_sha }}

  on-success:
    runs-on: ubuntu-latest
    needs: get-info
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Notify Slack - Successful deploy
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: #releases
          SLACK_COLOR: ${{ needs.get-info.outputs.prOutcome }}
          SLACK_USERNAME: gladia-ai-ci
          SLACK_TITLE: "New Gladia Image Released :rocket:"
          SLACK_MESSAGE: ${{ needs.get-info.outputs.prtitle }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":rocket:"

      - name: Trigger CD
        run: |
          curl -H "Authorization: token ${{ secrets.CD_SECRET }}" \
              -H 'Accept: application/vnd.github.everest-preview+json' \
              "https://api.github.com/repos/${{ secrets.CD_REPO }}/dispatches" \
              -d '{"event_type": "rollout", "client_payload": {"rollout": "public"}}'
