name: Gladia Base Builder

on:
  schedule:
    - cron: '30 3 * * 0'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

env:
  DOCKER_BUILD_OPT: "--no-cache"
  DOCKER_BUILD_IMAGE_NAME: gladia/base
  DOCKER_BUILD_IMAGE_TAG: latest

jobs:

  build:
    runs-on: [self-hosted, build, persist]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
         
      - name: Build Gladia Base image
        env:
          DOCKER_BUILDKIT: 1
        working-directory: ./src
        run: >-
          docker build --pull	
          ${{env.DOCKER_BUILD_OPT}}
          -t ${DOCKER_GLADIA_FQDN}/${{env.DOCKER_BUILD_IMAGE_NAME}}:${{env.DOCKER_BUILD_IMAGE_TAG}} -f docker/base.Dockerfile .

      - name: Push new base latest to Gladia registry
        run: docker push ${DOCKER_GLADIA_FQDN}/${{env.DOCKER_BUILD_IMAGE_NAME}}:${{env.DOCKER_BUILD_IMAGE_TAG}}
        
      - name: Tag new base latest to Docker registry
        run: docker tag ${DOCKER_GLADIA_FQDN}/${{env.DOCKER_BUILD_IMAGE_NAME}}:${{env.DOCKER_BUILD_IMAGE_TAG}} gladiaio/gladia-base:latest    
        
      - name: Push new base latest to Docker registry
        run: docker push gladiaio/gladia-base:latest
