name: Gladia Promote & deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      pr:
        description: "Force promote & deploy this PR"
        required: true

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false

env:
  TAG_PROMOTED: ""
  TAG_PROMOTE: latest
  TAG: ${{ inputs.pr }}

jobs:
  promote-gladia-image:
    runs-on: [self-hosted, build, ephemeral]
    if: ${{ (github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch') }}
    env:
      REGISTRY_URL: https://${DOCKER_GLADIA_FQDN}
    steps:
      - name: Assert Image, TAG and NS
        run: |
          if [ "$TAG" == "" ]; then
            echo "TAG_PROMOTED=ci-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "TAG_PROMOTED=ci-$TAG" >> $GITHUB_ENV
          fi

      - name: Promote *gladia-base* image to Gladia Registry
        if: |
          contains(github.event.pull_request.labels.*.name, 'ci: build-base')
        env:
          REPOSITORY: base
        run: |
          MANIFEST=$(curl -ns -X GET "https://${DOCKER_GLADIA_FQDN}/api/v2.0/projects/gladia/repositories/${{ env.REPOSITORY }}/artifacts/${{ env.TAG_PROMOTED }}/tags" | sed "s/${{ env.TAG_PROMOTED }}/latest/g" | tr -d "[]")
          curl -n -X DELETE "${{ env.REGISTRY_URL }}/api/v2.0/projects/gladia/repositories/${{ env.REPOSITORY }}/artifacts/latest/tags/latest"
          curl -n -X POST "${{ env.REGISTRY_URL }}/api/v2.0/projects/gladia/repositories/${{ env.REPOSITORY }}/artifacts/${{ env.TAG_PROMOTED }}/tags" -H "Content-Type: application/json" -d "${MANIFEST}"

      - name: Promote *gladia* image to Gladia Registry
        env:
          REPOSITORY: gladia
        run: |
          MANIFEST=$(curl -ns -X GET "https://${DOCKER_GLADIA_FQDN}/api/v2.0/projects/gladia/repositories/${{ env.REPOSITORY }}/artifacts/${{ env.TAG_PROMOTED }}/tags" | sed "s/${{ env.TAG_PROMOTED }}/latest/g" | tr -d "[]")
          curl -n -X DELETE "${{ env.REGISTRY_URL }}/api/v2.0/projects/gladia/repositories/${{ env.REPOSITORY }}/artifacts/latest/tags/latest"
          curl -n -X POST "${{ env.REGISTRY_URL }}/api/v2.0/projects/gladia/repositories/${{ env.REPOSITORY }}/artifacts/${{ env.TAG_PROMOTED }}/tags" -H "Content-Type: application/json" -d "${MANIFEST}"

  promote-gladia-to-DH:
    needs: promote-gladia-image
    runs-on: [self-hosted, build, persist]
    steps:
      - name: Promote *gladia-base* image to DH Registry
        if: |
          contains(github.event.pull_request.labels.*.name, 'ci: build-base')
        run: |
          docker pull ${DOCKER_GLADIA_FQDN}/gladia/base:${{ env.TAG_PROMOTE }} &&
          docker tag ${DOCKER_GLADIA_FQDN}/gladia/base:${{ env.TAG_PROMOTE }} gladiaio/gladia-base:latest &&
          docker push gladiaio/gladia-base:latest

      - name: Promote *gladia* image to DH Registry
        run: |
          docker pull ${DOCKER_GLADIA_FQDN}/gladia/gladia:${{ env.TAG_PROMOTE }} &&
          docker tag ${DOCKER_GLADIA_FQDN}/gladia/gladia:${{ env.TAG_PROMOTE }} gladiaio/gladia:latest &&
          docker push gladiaio/gladia:latest