name: PR Linter

on:
  pull_request:
    types: [edited]
  workflow_call:

jobs:
  main:
    name: Validate PR title
    runs-on: [self-hosted, build, ephemeral]
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  notification:
    name: Notify
    runs-on: ubuntu-latest
    needs: [main]
    if: always()
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: jsoto@gladia.io
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{job.status}} on ${{github.repository}}, ${{github.triggering_actor}}, ${{github.run_id}}
          to: github-notifications@gladia.io,jsoto@gladia.io
          from: github-notifications@gladia.io
          body: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
