name: PR Linter

on:
  pull_request:
    types: [edited]
  workflow_call:

jobs:
  main:
    name: Validate PR title
    runs-on: [self-hosted, build, ephemeral]
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
