name: "Upload gladia-api-utils to Pypi"

on:
  push:
    branches: [main]

jobs:
  check_if_need_to_rebuild:
    name: Check changed files
    outputs:
      update_api_utils: ${{ steps.changed-api-utils.outputs.any_changed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the api_utils folder
        id: changed-api-utils
        uses: tj-actions/changed-files@v34
        with:
          files: |
            src/api_utils/**

  upload:
    name: Build and Upload package
    needs: check_if_need_to_rebuild
    if: ${{ (needs.check_if_need_to_rebuild.outputs.update_api_utils  == 'true') }}
    runs-on: ubuntu-latest

    steps:
      - name: build dist
        run: cd /app/api_utils && python setup.py sdist

      - name: upload dist
        run: cd /app/api_utils && twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} dist/*

  notification:
    name: Notify
    runs-on: ubuntu-latest
    needs: [upload]
    if: always()
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: jsoto@gladia.io
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{steps.check.outputs.status}} on ${{github.repository}}, ${{github.triggering_actor}}, ${{github.run_id}}
          to: github-notifications@gladia.io,jsoto@gladia.io
          from: github-notifications@gladia.io
          body: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
